### ISSUE TITLE
Bug: unexpected unknownError in the demo App

### ISSUE THREAD

**Issue by Adelrisk** [epotheke/epotheke-sdk#2]
The demo app fails during the card link process with the error

> The activation was interrupted with the following message: http://www.bsi.bund.de/ecard/api/1.1/resultminor/al/common#unknownError"

Tested on a Samsung Galaxy S10 with Android 12.

Logs withheld from the issue, until I've cleared their content.

**Comment by legion151** [comment]
There were problems with SecureMessaging which appeared for some cards. 
Fixed in: https://github.com/epotheke/epotheke-sdk/releases/tag/v1.1.2
